apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: gitops-project

  source:
    repoURL: https://github.com/shivamsoin/gitops-project.git
    targetRevision: main
    path: helm/claims

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true