apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  namespace: log-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: logger
          image: shivamsoin0408/log-generator:73d8ee1
          imagePullPolicy: IfNotPresent
