apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: gitops-project
  source:
    repoURL: https://github.com/grafana/helm-charts.git
    targetRevision: "main"
    path: charts/loki-stack
    helm:
      valuesObject: 
        grafana:
          enabled: false
          sidecar:
            datasources: 
              enabled: false  
        promtail:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
