name: python app package

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Build App container
        run: docker build -t log-generator .
